Name: locust

image:
  repository: quay.io/honestbee/locust
  tag: 0.7.5
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  name: master-web
  type: NodePort
  externalPort: 8089
  internalPort: 8089
  nodePort: 0
  annotations: {}
  extraLabels: {}
master:
  config:
    target-host: https://site.example.com
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
worker:
  config:

    # all files from tasks folder are mounted under `/locust-tasks`
    locust-script: "/locust-tasks/task001.py"
  replicaCount: 2
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
configMap:
  tasksfiles:
    task001.py: |
      import json
      from locust import HttpLocust, TaskSet, task

      class Grasshoppers(TaskSet):
            def on_start(self):
              self.client.verify = False

            @task
            def get_api_Amenities_filters(self):
              self.client.get("/api/Amenities/filters", name="/api/Amenities/filters")

      class AwesomeUser(HttpLocust):
         task_set = Grasshoppers
         min_wait = 1 * 1000
         max_wait = 5 * 1000
