apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "locust.worker-configmap" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "locust.fullname" . }}
data:
{{ toYaml .Values.configMap.tasksfiles | indent 2 }}

